### PR TITLE
Fix path probem

### PR DESCRIPTION
**Pull request by nikolicjakov**
Deployment to OpenShift would not work since build is going to fail while looking for Dockerfile.

### CODE REVIEW

**Comment by whyjustin** [comment]
To note, this Dockerfile is now available as Dockerfile.rh.centos and kept up to date on master in [sonatype/docker-nexus3](https://github.com/sonatype/docker-nexus3/blob/master/Dockerfile.rh.centos).

**Comment by whyjustin** [comment]
And templates are available [sonatype-nexus-community/container-management-reference-architecture](https://github.com/sonatype-nexus-community/container-management-reference-architecture/tree/master/OpenShift) which will pull the Dockerfile and build from the appropriate location (or pull from the Red Hat Container Catalog for the RHEL images).

**Comment by nikolicjakov** [comment]
@whyjustin Thanks for info, i have tested this template that you are talking about just now and it is not stable. Build is failing during chef cookbook execution when it comes to installing java.

```
Recipe: java::oracle
  * log[WARNING - Downloading directly from Oracle is unreliable. Change download url.] action write[2018-04-20T20:07:02+00:00] WARN: WARNING - Downloading directly from Oracle is unreliable. Change download url.
[2018-04-20T20:07:02+00:00] WARN: WARNING - Downloading directly from Oracle is unreliable. Change download url.
  
Recipe: java::set_java_home
  * directory[/etc/profile.d] action create (up to date)
  * template[/etc/profile.d/jdk.sh] action create
    - create new file /etc/profile.d/jdk.sh
    - update content in file /etc/profile.d/jdk.sh from none to b2915a
    --- /etc/profile.d/jdk.sh	2018-04-20 20:07:02.039130799 +0000
    +++ /etc/profile.d/.chef-jdk20180420-72-n4yp7s.sh	2018-04-20 20:07:02.039130799 +0000
    @@ -1 +1,2 @@
    +export JAVA_HOME=/opt/java
    - change mode from '' to '0755'
Recipe: java::oracle
  * yum_package[tar] action install (up to date)
  * java_ark[jdk] action install
    * yum_package[curl for download_direct_from_oracle] action install (up to date)
    - download oracle tarball straight from the server[2018-04-20T20:07:07+00:00] FATAL: Failed to extract file server-jre-8u162-linux-x64.tar.gz!
[2018-04-20T20:07:07+00:00] FATAL: Failed to extract file server-jre-8u162-linux-x64.tar.gz!

  Running handlers:
[2018-04-20T20:07:07+00:00] ERROR: Running exception handlers
[2018-04-20T20:07:07+00:00] ERROR: Running exception handlers
  Running handlers complete
[2018-04-20T20:07:07+00:00] ERROR: Exception handlers complete
[2018-04-20T20:07:07+00:00] ERROR: Exception handlers complete
  Chef Client failed. 2 resources updated in 13 seconds
[2018-04-20T20:07:07+00:00] FATAL: Stacktrace dumped to /etc/chef/local-mode-cache/cache/chef-stacktrace.out
[2018-04-20T20:07:07+00:00] FATAL: Stacktrace dumped to /etc/chef/local-mode-cache/cache/chef-stacktrace.out
[2018-04-20T20:07:07+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2018-04-20T20:07:07+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
Removing intermediate container 169519c25aeb
```

**Comment by whyjustin** [comment]
@nikolicjakov this should now be fixed - https://github.com/sonatype/docker-nexus3/commit/af1f6b460c1ed5dca67953c43a1a53a28728f849

**Pull request merged**
